# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='createNewPass', kernelModule='plugin', kernelFunction='createNewModel', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgTextField(p='DialogBox', fieldType='String', ncols=12, labelText='New Model Name', keyword='newModel', default='Model-2')
RsgTextField(p='DialogBox', fieldType='String', ncols=12, labelText='Last Model Name', keyword='lastModel', default='Model-1')
RsgTextField(p='DialogBox', fieldType='String', ncols=12, labelText='Last Job Name', keyword='lastJob', default='Job-1')
RsgTextField(p='DialogBox', fieldType='String', ncols=12, labelText='Part Name', keyword='part', default='Part-1')
RsgTextField(p='DialogBox', fieldType='String', ncols=12, labelText='Part Material Name', keyword='material', default='Material-1')
dialogBox.show()